language: java
jdk:
- oraclejdk8
notifications:
  webhooks:
    urls:
      - https://discordapp.com/api/webhooks/322433178260340747/Yqtx9TPJKfgCN5JnAV2oMSF6Zzo5-WGkfMGP2Knb28PJeqcgQ06zIAP4Jqta6hNr6NOb
    on_success: always # change # default: always
    on_failure: always # default: always
    on_start: always # change # default: never
    on_cancel: always # default: always
    on_error: always # default: always
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
- chmod +x gradlew
script: ./gradlew check
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/